export enum EMessage {
  AssignPlayerID,
  AddOpponentID,
  CreateHitbox,
  PlayerHurt,
  ServerUpdateHudDamage,
  CreateEntity,
  RemoveEntity,
  CreateHud, 
  NewHudPlayer, 
  UpdateHudDamage,
  ServerRemoveHudPlayer,
  RemoveHudPlayer,
  UpdateSprite,
  RemoveAttackHitbox,
  PlayerDead,
}
